using System.Collections.Generic;
using System.Linq;
using System.Text;
using StardewValley;

namespace LivingNPCs.Behavior;

internal sealed class BehaviorMemory
{
    private readonly Dictionary<string, List<BehaviorMemoryEntry>> entriesByNpc = new();
    private readonly Dictionary<string, int> dailyCountsByNpc = new();

    public void ResetDaily()
    {
        this.dailyCountsByNpc.Clear();
    }

    public bool HasDailyBudget(NPC npc, int maxPerDay)
    {
        return !this.dailyCountsByNpc.TryGetValue(npc.Name, out int count) || count < maxPerDay;
    }

    public BehaviorMemoryEntry Record(NPC npc, BehaviorIntent intent)
    {
        var entry = new BehaviorMemoryEntry(
            npc.Name,
            intent.Type.ToString(),
            intent.Reason,
            Game1.year,
            Game1.season.ToString(),
            Game1.dayOfMonth,
            Game1.timeOfDay
        );

        if (!this.entriesByNpc.TryGetValue(npc.Name, out var entries))
        {
            entries = new List<BehaviorMemoryEntry>();
            this.entriesByNpc[npc.Name] = entries;
        }

        entries.Add(entry);
        if (entries.Count > 12)
        {
            entries.RemoveAt(0);
        }

        this.dailyCountsByNpc[npc.Name] = this.dailyCountsByNpc.TryGetValue(npc.Name, out int count) ? count + 1 : 1;
        return entry;
    }

    public string BuildPromptContext(NPC npc)
    {
        if (!this.entriesByNpc.TryGetValue(npc.Name, out var entries) || entries.Count == 0)
        {
            return string.Empty;
        }

        var prompt = new StringBuilder();
        prompt.AppendLine("## LivingNPCs behavior context");
        prompt.AppendLine($"{npc.displayName} has recently taken small in-world actions generated by the LivingNPCs behavior system.");
        prompt.AppendLine("Use these as quiet scene context for the next reply. Do not mention LivingNPCs, prompts, mods, JSON, or AI systems.");
        prompt.AppendLine("If the action is relevant, the character may naturally acknowledge it as something they just did or felt.");

        foreach (var entry in entries.TakeLast(4))
        {
            prompt.AppendLine($"- {entry.Season} {entry.Day}, {entry.TimeOfDay}: {entry.Action}; reason: {entry.Reason}");
        }

        prompt.AppendLine("Keep the next line in character and consistent with the current Stardew Valley scene.");
        return prompt.ToString();
    }
}

internal sealed record BehaviorMemoryEntry(
    string NpcName,
    string Action,
    string Reason,
    int Year,
    string Season,
    int Day,
    int TimeOfDay
);
